// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma 7 dropped the separate `directUrl` option; the CLI now runs
  // migrations against whatever URL is set here. Supabase's pgBouncer
  // (transaction-mode) pooler doesn't support the session features Migrate
  // needs, so this must be the session-mode/direct connection string.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
