export type LedgerEntryType =
  | 'connector_joined'
  | 'referral_submitted'
  | 'referral_won'
  | 'commission_tier1_paid'
  | 'commission_tier2_paid'
  | 'eco_pledge_honoured'
  | 'review_submitted'
  | 'vendor_joined'
  | 'agreement_signed'
  | 'whatsapp_message_received'
  | 'grade_promoted'
